ScreenCapture:
	/opt/external-toolchain/bin/arm-none-linux-gnueabihf-g++ ScreenCapture.cpp -std=c++11 -I ~/workspace/gflags/build/include -L ~/workspace/gflags/build/lib -lgflags -lpthread -o ScreenCapture
clean:
	@rm ScreenCapture
